# version: '3'
# services:
#   db:
#     image: postgres:alpine
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '4321:4321'
#     restart: always
#   node-app:
#     image: authen:v1.0.0
#     ports:
#       - '3000:8080'
#     depends_on:
#       - db
version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - NODE_ENV=development
    environment:
      - PORT:3000
      - DB_HOST=postgres
      # - DB_PORT:5432
      - DB_USER:postgres
      - DB_PW:postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npm run start
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test1
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data/postgres
