# version: '3'
# services:
#   db:
#     image: postgres:alpine
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '4321:4321'
#     restart: always
#   node-app:
#     image: authen:v1.0.0
#     ports:
#       - '3000:8080'
#     depends_on:
#       - db
version: '3'
services:
  api:
    environment:
      - PORT:${PORT}
      - DB_CONNECTION:${DB_CONNECTION}
      - DB_HOST:${DB_HOST}
      - DB_USERNAME:${DB_USERNAME}
      - DB_PASSWORD:${DB_PASSWORD}
      - DB_DATABASE:${DB_DATABASE}
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - NODE_ENV=development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    links:
      - postgres:postgres
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npm run start
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER:${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data/postgres
